### ISSUE TITLE
Using ob_type='pixels' outputs images of entrire maze as observations

### ISSUE THREAD

**Issue by shashank879** [seohongpark/ogbench#1]
I am using Ogbench (v1.0.1) in python (v3.12).
When I instantiate the environment as:

```python
env = ogbench.make_env_and_datasets(
    'antmaze-large-navigate-v0',
    env_only=True,
    ob_type='pixels',
)
```

While the env.observation_space is correct:
```python
print(env.observation_space)
# Output: Box(0, 255, (64, 64, 3), uint8)
```

The renderer images generated by calling reset (and step) contain the entire maze as opposed to the cropped 64x64 image around the agent (as mentioned in the paper).

```python
obs, info = env.reset(options=dict(render_goal=True,))
print(obs.shape)
print(info['goal'].shape)
display(Image.fromarray(obs))
display(Image.fromarray(info['goal']))
# Outputs:
# (200, 200, 3)
# (200, 200, 3)
```

Observation:
![image](https://github.com/user-attachments/assets/a1d5ecce-894d-4cb8-85df-1ddc2ae52135)
Goal:
![image](https://github.com/user-attachments/assets/00fadcde-3474-4a83-80cf-09bc5e851eae)

Could you please help me fix this issue?

**Comment by seohongpark** [comment]
Hi Shashank, you need to make an environment with `ogbench.make_env_and_datasets('visual-antmaze-large-navigate-v0')`, instead of specifying `ob_type` manually.
